---
# handlers file for hestiacp
- name: "reboot server"
  reboot:
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 5
    post_reboot_delay: 30
    test_command: whoami

- name: "restart mariadb"
  service:
    name: mariadb
    state: restarted

- name: "restart systemd daemon"
  become: true
  systemd:
    daemon_reload: yes

- name: "restart nginx"
  service:
    name: nginx
    state: restarted

- name: "restart apache"
  become: true
  service:
    name: apache2
    state: restarted
